version: '3.8'

services:
  authservice:
    build:
      context: ./snv2_backend/AuthService
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=development
    networks:
      - default

  postservice:
    build:
      context: ./snv2_backend/PostService
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
    networks:
      - default

  socialservice:
    build:
      context: ./snv2_backend/SocialService
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
    networks:
      - default

  userservice:
    build:
      context: ./snv2_backend/UserService
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=development
    networks:
      - default

  frontend:
    build:
      context: ./snv2_frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - authservice
      - postservice
      - socialservice
      - userservice
    networks:
      - default

networks:
  default:
    driver: bridge
